# Generated by Django 6.1 on 2026-08-06 06:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataIngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('job_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial success')], default='running', max_length=20)),
                ('assets_attempted', models.PositiveIntegerField(default=0)),
                ('assets_succeeded', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('external_ids', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol'], name='core_asset_symbol_3dd9ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_type', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_issues', to='core.asset')),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dataingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_addresses', to='core.asset')),
                ('blockchain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.blockchain')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('blockchain', 'address'), name='unique_contract_per_chain')],
            },
        ),
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_usd', models.DecimalField(decimal_places=18, max_digits=36)),
                ('market_cap_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('fully_diluted_valuation_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('volume_24h_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('circulating_supply', models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True)),
                ('total_supply', models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True)),
                ('max_supply', models.DecimalField(blank=True, decimal_places=8, max_digits=36, null=True)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='core.asset')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['asset', 'observed_at'], name='core_market_asset_i_5140f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'source', 'observed_at'), name='unique_snapshot_per_source_time')],
            },
        ),
    ]
