# Generated by Django 6.0.8 on 2026-08-06 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(choices=[('10x_potential', '10X Potential'), ('undervaluation', 'Undervaluation'), ('momentum', 'Momentum'), ('risk', 'Risk')], max_length=30)),
                ('model_version', models.CharField(max_length=20)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_snapshots', to='core.asset')),
                ('market_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score_snapshots', to='core.marketsnapshot')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=200, null=True)),
                ('insufficient_data', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('score_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_factors', to='core.scoresnapshot')),
            ],
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['asset', 'model_name', 'computed_at'], name='core_scores_asset_i_4b0524_idx'),
        ),
        migrations.AddIndex(
            model_name='scoresnapshot',
            index=models.Index(fields=['model_name', 'model_version', 'computed_at'], name='core_scores_model_n_156e30_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoresnapshot',
            constraint=models.UniqueConstraint(fields=('asset', 'model_name', 'model_version', 'market_snapshot'), name='unique_score_per_asset_model_version_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='scorefactor',
            constraint=models.UniqueConstraint(fields=('score_snapshot', 'name'), name='unique_factor_per_score_snapshot'),
        ),
    ]
