# Generated by Django 6.0.8 on 2026-08-07 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scoresnapshot_scorefactor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('chains', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocols', to='core.asset')),
            ],
        ),
        migrations.CreateModel(
            name='TVLSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tvl_usd', models.DecimalField(decimal_places=2, max_digits=36)),
                ('change_1d_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('change_7d_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tvl_snapshots', to='core.protocol')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['protocol', 'observed_at'], name='core_tvlsna_protoco_3ee58d_idx')],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'source', 'observed_at'), name='unique_tvl_snapshot_per_source_time')],
            },
        ),
    ]
