# Generated by Django 6.0.8 on 2026-08-07 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_protocol_tvlsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fees_24h_usd', models.DecimalField(decimal_places=2, max_digits=36)),
                ('fees_7d_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('fees_30d_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=36, null=True)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_snapshots', to='core.protocol')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['protocol', 'observed_at'], name='core_feesna_protoco_1f5f00_idx')],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'source', 'observed_at'), name='unique_fee_snapshot_per_source_time')],
            },
        ),
        migrations.CreateModel(
            name='RevenueSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revenue_24h_usd', models.DecimalField(decimal_places=2, max_digits=36)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_snapshots', to='core.protocol')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['protocol', 'observed_at'], name='core_revenu_protoco_239e4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('protocol', 'source', 'observed_at'), name='unique_revenue_snapshot_per_source_time')],
            },
        ),
    ]
