# Generated by Django 6.0.8 on 2026-08-07 11:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feesnapshot_revenuesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolderSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder_count', models.PositiveIntegerField(blank=True, null=True)),
                ('top_10_concentration_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_snapshots', to='core.contractaddress')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['contract_address', 'observed_at'], name='core_holder_contrac_286b34_idx')],
                'constraints': [models.UniqueConstraint(fields=('contract_address', 'source', 'observed_at'), name='unique_holder_snapshot_per_source_time')],
            },
        ),
    ]
