# Generated by Django 6.0.8 on 2026-08-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_holdersnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='raw_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(blank=True, choices=[('DeFi', 'DeFi'), ('L1', 'L1'), ('L2', 'L2'), ('RWA', 'RWA'), ('DePIN', 'DePIN'), ('AI', 'AI'), ('Infrastructure', 'Infrastructure'), ('Payments', 'Payments'), ('Stablecoin Infrastructure', 'Stablecoin Infrastructure'), ('Gaming', 'Gaming'), ('Social', 'Social'), ('Privacy', 'Privacy'), ('Oracle', 'Oracle'), ('Interoperability', 'Interoperability'), ('DEX', 'DEX'), ('Lending', 'Lending'), ('Derivatives', 'Derivatives'), ('Meme', 'Meme')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['sector'], name='core_asset_sector_dbb849_idx'),
        ),
    ]
