# Generated by Django 6.0.8 on 2026-08-09 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_asset_raw_categories_asset_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DeveloperActivitySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveIntegerField()),
                ('forks', models.PositiveIntegerField()),
                ('open_issues', models.PositiveIntegerField()),
                ('is_archived', models.BooleanField(default=False)),
                ('repo_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('commits_4w', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_activity_snapshots', to='core.asset')),
            ],
            options={
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['asset', 'observed_at'], name='core_develo_asset_i_03fa14_idx')],
                'constraints': [models.UniqueConstraint(fields=('asset', 'source', 'observed_at'), name='unique_dev_activity_per_source_time')],
            },
        ),
    ]
