# Generated by Django 6.0.8 on 2026-08-10 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_asset_github_repo_url_developeractivitysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalyst',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('catalyst_type', models.CharField(choices=[('mainnet', 'Mainnet'), ('token_launch', 'Token Launch'), ('major_upgrade', 'Major Upgrade'), ('protocol_release', 'Protocol Release'), ('exchange_listing', 'Exchange Listing'), ('partnership', 'Partnership'), ('product_launch', 'Product Launch'), ('token_unlock', 'Token Unlock'), ('governance_event', 'Governance Event'), ('institutional_integration', 'Institutional Integration'), ('ecosystem_expansion', 'Major Ecosystem Expansion')], max_length=30)),
                ('event_date', models.DateField()),
                ('source_url', models.URLField()),
                ('confidence', models.CharField(choices=[('confirmed', 'Confirmed by official source'), ('likely', 'Likely (strong secondary sourcing)'), ('speculative', 'Speculative (unconfirmed rumor, tracked for awareness only)')], max_length=20)),
                ('impact_estimate', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text="Curator's qualitative estimate, not a backtested prediction — see Confidence's own docstring for why this stays categorical rather than a fabricated numeric score.", max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='upcoming', max_length=20)),
                ('added_by', models.CharField(blank=True, help_text='Who curated this entry, for audit.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalysts', to='core.asset')),
            ],
            options={
                'ordering': ['event_date'],
                'indexes': [models.Index(fields=['asset', 'event_date'], name='core_cataly_asset_i_21c2d3_idx'), models.Index(fields=['status', 'event_date'], name='core_cataly_status_6690a0_idx')],
            },
        ),
    ]
