# Generated by Django 5.0.14 on 2026-08-20 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_catalyst"),
    ]

    operations = [
        migrations.CreateModel(
            name="DEXPairSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("liquidity_usd", models.DecimalField(decimal_places=2, max_digits=36)),
                (
                    "volume_24h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=36, null=True
                    ),
                ),
                (
                    "volume_6h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=36, null=True
                    ),
                ),
                (
                    "volume_1h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=36, null=True
                    ),
                ),
                (
                    "price_change_24h_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_6h_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price_change_1h_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("txns_24h_buys", models.PositiveIntegerField(blank=True, null=True)),
                ("txns_24h_sells", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "earliest_pair_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("pair_count", models.PositiveIntegerField(default=1)),
                ("chains", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(max_length=50)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dex_pair_snapshots",
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
            },
        ),
        migrations.CreateModel(
            name="MarketRegimeSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("btc_price_usd", models.DecimalField(decimal_places=2, max_digits=36)),
                ("eth_price_usd", models.DecimalField(decimal_places=2, max_digits=36)),
                (
                    "btc_change_7d_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "eth_change_7d_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("btc_above_50dma", models.BooleanField(blank=True, null=True)),
                (
                    "btc_50dma_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=36, null=True
                    ),
                ),
                (
                    "eth_btc_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                (
                    "eth_btc_change_7d_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "btc_volume_dominance_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=7, null=True
                    ),
                ),
                (
                    "total_usdt_volume_24h_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=36, null=True
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("bullish", "Bullish"),
                            ("bearish", "Bearish"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "regime_confidence",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("source", models.CharField(max_length=50)),
                ("observed_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["observed_at"], name="core_market_observe_0381bc_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="marketregimesnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "observed_at"),
                name="unique_regime_snapshot_per_source_time",
            ),
        ),
        migrations.AddIndex(
            model_name="dexpairsnapshot",
            index=models.Index(
                fields=["asset", "observed_at"], name="core_dexpai_asset_i_ed6439_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dexpairsnapshot",
            constraint=models.UniqueConstraint(
                fields=("asset", "source", "observed_at"),
                name="unique_dex_snapshot_per_source_time",
            ),
        ),
    ]
