# Generated by Django 5.0.14 on 2026-08-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_dex_pair_and_market_regime_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        help_text="External user ID from the main site's JWT.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("none", "No Subscription"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "plan",
                    models.CharField(
                        default="monthly",
                        help_text="Subscription plan name (e.g. monthly, yearly).",
                        max_length=50,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="core_subscr_user_id_1b4f08_idx"
                    ),
                    models.Index(
                        fields=["status", "expires_at"],
                        name="core_subscr_status_1234a6_idx",
                    ),
                ],
            },
        ),
    ]
