# Generated by Django 5.0.14 on 2026-08-31 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_add_subscription_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="External user ID from the main site's JWT.",
                        max_length=255,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. 'SOL 10X score > 80'.",
                        max_length=120,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("score_10x", "10X Potential score"),
                            ("score_undervaluation", "Undervaluation score"),
                            ("score_momentum", "Momentum score"),
                            ("score_risk", "Risk score"),
                            ("market_cap_pct_change_24h", "Market cap 24h % change"),
                            ("volume_pct_change_24h", "Volume 24h % change"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "greater than"),
                            ("gte", "greater than or equal"),
                            ("lt", "less than"),
                            ("lte", "less than or equal"),
                        ],
                        default="gt",
                        max_length=5,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("telegram", "Telegram")],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Minimum minutes between two fires of this rule, to prevent alert spam.",
                    ),
                ),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="The asset to watch, or NULL to watch all tracked assets.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("metric", models.CharField(max_length=30)),
                ("operator", models.CharField(max_length=5)),
                ("threshold", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "observed_value",
                    models.DecimalField(decimal_places=6, max_digits=30),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("failed", "Delivery failed"),
                            ("error", "Evaluation error"),
                        ],
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("channels", models.JSONField(blank=True, default=list)),
                ("error_detail", models.TextField(blank=True)),
                ("fired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_events",
                        to="core.asset",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-fired_at"],
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["user_id", "is_active"], name="core_alertr_user_id_c7f2ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["asset", "is_active"], name="core_alertr_asset_i_da0a3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertevent",
            index=models.Index(
                fields=["rule", "fired_at"], name="core_alerte_rule_id_d1880e_idx"
            ),
        ),
    ]
