# Generated by Django 5.0.14 on 2026-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alertrule_alertevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertrule",
            name="cooldown_minutes",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Minimum minutes between two fires of this rule FOR THE SAME ASSET, to prevent alert spam.",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="last_fired_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Most recent fire across any asset — informational only. Cooldown is enforced per (rule, asset) using the alert history, so a global rule firing for one asset doesn't silence it for others.",
                null=True,
            ),
        ),
    ]
