# Generated by Django 5.0.14 on 2026-08-31 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_alertrule_cooldown_minutes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        db_index=True,
                        help_text="External user ID from the main site's JWT.",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label, e.g. 'Prod analytics endpoint'.",
                        max_length=120,
                    ),
                ),
                ("target_url", models.URLField()),
                ("secret", models.CharField(blank=True, default="", max_length=128)),
                (
                    "event_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of event types to receive, e.g. ["score.changed"]. Empty = all events.',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.asset",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_active"],
                        name="core_webhoo_user_id_4edeca_idx",
                    )
                ],
            },
        ),
    ]
