# Generated by Django 5.0.14 on 2026-08-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_webhooksubscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUsage",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("date", models.DateField()),
                ("call_count", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="apiusage",
            constraint=models.UniqueConstraint(
                fields=("user_id", "date"), name="unique_daily_usage_per_user"
            ),
        ),
    ]
