# Generated by Django 5.0.14 on 2026-09-01 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_apiusage_apiusage_unique_daily_usage_per_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBinding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                (
                    "telegram_username",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "verify_token",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "is_verified"],
                        name="core_telegr_user_id_6b3be7_idx",
                    )
                ],
            },
        ),
    ]
